// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: internal/client/apexverifier/proto/apex.proto

package apexpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        string                 `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAccountRequest) Reset() {
	*x = VerifyAccountRequest{}
	mi := &file_internal_client_apexverifier_proto_apex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAccountRequest) ProtoMessage() {}

func (x *VerifyAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_apexverifier_proto_apex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAccountRequest.ProtoReflect.Descriptor instead.
func (*VerifyAccountRequest) Descriptor() ([]byte, []int) {
	return file_internal_client_apexverifier_proto_apex_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyAccountRequest) GetPlayer() string {
	if x != nil {
		return x.Player
	}
	return ""
}

func (x *VerifyAccountRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *VerifyAccountRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type VerifyAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Player        string                 `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAccountResponse) Reset() {
	*x = VerifyAccountResponse{}
	mi := &file_internal_client_apexverifier_proto_apex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAccountResponse) ProtoMessage() {}

func (x *VerifyAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_apexverifier_proto_apex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAccountResponse.ProtoReflect.Descriptor instead.
func (*VerifyAccountResponse) Descriptor() ([]byte, []int) {
	return file_internal_client_apexverifier_proto_apex_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyAccountResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *VerifyAccountResponse) GetPlayer() string {
	if x != nil {
		return x.Player
	}
	return ""
}

func (x *VerifyAccountResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *VerifyAccountResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

var File_internal_client_apexverifier_proto_apex_proto protoreflect.FileDescriptor

const file_internal_client_apexverifier_proto_apex_proto_rawDesc = "" +
	"\n" +
	"-internal/client/apexverifier/proto/apex.proto\x12\x04apex\"`\n" +
	"\x14VerifyAccountRequest\x12\x16\n" +
	"\x06player\x18\x01 \x01(\tR\x06player\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\"s\n" +
	"\x15VerifyAccountResponse\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x16\n" +
	"\x06player\x18\x02 \x01(\tR\x06player\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level2X\n" +
	"\fApexVerifier\x12H\n" +
	"\rVerifyAccount\x12\x1a.apex.VerifyAccountRequest\x1a\x1b.apex.VerifyAccountResponseB^Z\\github.com/rzhaka-turiki/rzhaka_tournaments/internal/client/apexverifier/proto/apexpb;apexpbb\x06proto3"

var (
	file_internal_client_apexverifier_proto_apex_proto_rawDescOnce sync.Once
	file_internal_client_apexverifier_proto_apex_proto_rawDescData []byte
)

func file_internal_client_apexverifier_proto_apex_proto_rawDescGZIP() []byte {
	file_internal_client_apexverifier_proto_apex_proto_rawDescOnce.Do(func() {
		file_internal_client_apexverifier_proto_apex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_client_apexverifier_proto_apex_proto_rawDesc), len(file_internal_client_apexverifier_proto_apex_proto_rawDesc)))
	})
	return file_internal_client_apexverifier_proto_apex_proto_rawDescData
}

var file_internal_client_apexverifier_proto_apex_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_client_apexverifier_proto_apex_proto_goTypes = []any{
	(*VerifyAccountRequest)(nil),  // 0: apex.VerifyAccountRequest
	(*VerifyAccountResponse)(nil), // 1: apex.VerifyAccountResponse
}
var file_internal_client_apexverifier_proto_apex_proto_depIdxs = []int32{
	0, // 0: apex.ApexVerifier.VerifyAccount:input_type -> apex.VerifyAccountRequest
	1, // 1: apex.ApexVerifier.VerifyAccount:output_type -> apex.VerifyAccountResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_client_apexverifier_proto_apex_proto_init() }
func file_internal_client_apexverifier_proto_apex_proto_init() {
	if File_internal_client_apexverifier_proto_apex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_client_apexverifier_proto_apex_proto_rawDesc), len(file_internal_client_apexverifier_proto_apex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_client_apexverifier_proto_apex_proto_goTypes,
		DependencyIndexes: file_internal_client_apexverifier_proto_apex_proto_depIdxs,
		MessageInfos:      file_internal_client_apexverifier_proto_apex_proto_msgTypes,
	}.Build()
	File_internal_client_apexverifier_proto_apex_proto = out.File
	file_internal_client_apexverifier_proto_apex_proto_goTypes = nil
	file_internal_client_apexverifier_proto_apex_proto_depIdxs = nil
}
