// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: internal/client/apexverifier/proto/apex.proto

package apexpb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApexVerifier_VerifyAccount_FullMethodName = "/apex.ApexVerifier/VerifyAccount"
)

// ApexVerifierClient is the client API for ApexVerifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApexVerifierClient interface {
	VerifyAccount(ctx context.Context, in *VerifyAccountRequest, opts ...grpc.CallOption) (*VerifyAccountResponse, error)
}

type apexVerifierClient struct {
	cc grpc.ClientConnInterface
}

func NewApexVerifierClient(cc grpc.ClientConnInterface) ApexVerifierClient {
	return &apexVerifierClient{cc}
}

func (c *apexVerifierClient) VerifyAccount(ctx context.Context, in *VerifyAccountRequest, opts ...grpc.CallOption) (*VerifyAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyAccountResponse)
	err := c.cc.Invoke(ctx, ApexVerifier_VerifyAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApexVerifierServer is the server API for ApexVerifier service.
// All implementations must embed UnimplementedApexVerifierServer
// for forward compatibility.
type ApexVerifierServer interface {
	VerifyAccount(context.Context, *VerifyAccountRequest) (*VerifyAccountResponse, error)
	mustEmbedUnimplementedApexVerifierServer()
}

// UnimplementedApexVerifierServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApexVerifierServer struct{}

func (UnimplementedApexVerifierServer) VerifyAccount(context.Context, *VerifyAccountRequest) (*VerifyAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyAccount not implemented")
}
func (UnimplementedApexVerifierServer) mustEmbedUnimplementedApexVerifierServer() {}
func (UnimplementedApexVerifierServer) testEmbeddedByValue()                      {}

// UnsafeApexVerifierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApexVerifierServer will
// result in compilation errors.
type UnsafeApexVerifierServer interface {
	mustEmbedUnimplementedApexVerifierServer()
}

func RegisterApexVerifierServer(s grpc.ServiceRegistrar, srv ApexVerifierServer) {
	// If the following call panics, it indicates UnimplementedApexVerifierServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApexVerifier_ServiceDesc, srv)
}

func _ApexVerifier_VerifyAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApexVerifierServer).VerifyAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApexVerifier_VerifyAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApexVerifierServer).VerifyAccount(ctx, req.(*VerifyAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApexVerifier_ServiceDesc is the grpc.ServiceDesc for ApexVerifier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApexVerifier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apex.ApexVerifier",
	HandlerType: (*ApexVerifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyAccount",
			Handler:    _ApexVerifier_VerifyAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/client/apexverifier/proto/apex.proto",
}
