// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: internal/client/matchapi/proto/match_service.proto

package matchapipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activation    string                 `protobuf:"bytes,1,opt,name=activation,proto3" json:"activation,omitempty"`
	Expiration    string                 `protobuf:"bytes,2,opt,name=expiration,proto3" json:"expiration,omitempty"`
	StatsToken    string                 `protobuf:"bytes,3,opt,name=stats_token,json=statsToken,proto3" json:"stats_token,omitempty"`
	AdminToken    string                 `protobuf:"bytes,4,opt,name=admin_token,json=adminToken,proto3" json:"admin_token,omitempty"`
	PlayerToken   string                 `protobuf:"bytes,5,opt,name=player_token,json=playerToken,proto3" json:"player_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTokenRequest) Reset() {
	*x = AddTokenRequest{}
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTokenRequest) ProtoMessage() {}

func (x *AddTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTokenRequest.ProtoReflect.Descriptor instead.
func (*AddTokenRequest) Descriptor() ([]byte, []int) {
	return file_internal_client_matchapi_proto_match_service_proto_rawDescGZIP(), []int{0}
}

func (x *AddTokenRequest) GetActivation() string {
	if x != nil {
		return x.Activation
	}
	return ""
}

func (x *AddTokenRequest) GetExpiration() string {
	if x != nil {
		return x.Expiration
	}
	return ""
}

func (x *AddTokenRequest) GetStatsToken() string {
	if x != nil {
		return x.StatsToken
	}
	return ""
}

func (x *AddTokenRequest) GetAdminToken() string {
	if x != nil {
		return x.AdminToken
	}
	return ""
}

func (x *AddTokenRequest) GetPlayerToken() string {
	if x != nil {
		return x.PlayerToken
	}
	return ""
}

type AddTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       int32                  `protobuf:"varint,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTokenResponse) Reset() {
	*x = AddTokenResponse{}
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTokenResponse) ProtoMessage() {}

func (x *AddTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTokenResponse.ProtoReflect.Descriptor instead.
func (*AddTokenResponse) Descriptor() ([]byte, []int) {
	return file_internal_client_matchapi_proto_match_service_proto_rawDescGZIP(), []int{1}
}

func (x *AddTokenResponse) GetTokenId() int32 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

func (x *AddTokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OnlyActive    bool                   `protobuf:"varint,1,opt,name=only_active,json=onlyActive,proto3" json:"only_active,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensRequest) Reset() {
	*x = ListTokensRequest{}
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensRequest) ProtoMessage() {}

func (x *ListTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensRequest.ProtoReflect.Descriptor instead.
func (*ListTokensRequest) Descriptor() ([]byte, []int) {
	return file_internal_client_matchapi_proto_match_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListTokensRequest) GetOnlyActive() bool {
	if x != nil {
		return x.OnlyActive
	}
	return false
}

func (x *ListTokensRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTokensRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type TokenInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Activation    string                 `protobuf:"bytes,2,opt,name=activation,proto3" json:"activation,omitempty"`
	Expiration    string                 `protobuf:"bytes,3,opt,name=expiration,proto3" json:"expiration,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenInfo) Reset() {
	*x = TokenInfo{}
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenInfo) ProtoMessage() {}

func (x *TokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenInfo.ProtoReflect.Descriptor instead.
func (*TokenInfo) Descriptor() ([]byte, []int) {
	return file_internal_client_matchapi_proto_match_service_proto_rawDescGZIP(), []int{3}
}

func (x *TokenInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TokenInfo) GetActivation() string {
	if x != nil {
		return x.Activation
	}
	return ""
}

func (x *TokenInfo) GetExpiration() string {
	if x != nil {
		return x.Expiration
	}
	return ""
}

func (x *TokenInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type ListTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*TokenInfo           `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensResponse) Reset() {
	*x = ListTokensResponse{}
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensResponse) ProtoMessage() {}

func (x *ListTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensResponse.ProtoReflect.Descriptor instead.
func (*ListTokensResponse) Descriptor() ([]byte, []int) {
	return file_internal_client_matchapi_proto_match_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListTokensResponse) GetTokens() []*TokenInfo {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *ListTokensResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListTokensResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ListMatchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	MapName       string                 `protobuf:"bytes,3,opt,name=map_name,json=mapName,proto3" json:"map_name,omitempty"`
	PlayerHash    string                 `protobuf:"bytes,4,opt,name=player_hash,json=playerHash,proto3" json:"player_hash,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,6,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	TokenId       int32                  `protobuf:"varint,7,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMatchesRequest) Reset() {
	*x = ListMatchesRequest{}
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMatchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMatchesRequest) ProtoMessage() {}

func (x *ListMatchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMatchesRequest.ProtoReflect.Descriptor instead.
func (*ListMatchesRequest) Descriptor() ([]byte, []int) {
	return file_internal_client_matchapi_proto_match_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListMatchesRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ListMatchesRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *ListMatchesRequest) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *ListMatchesRequest) GetPlayerHash() string {
	if x != nil {
		return x.PlayerHash
	}
	return ""
}

func (x *ListMatchesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListMatchesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListMatchesRequest) GetTokenId() int32 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

type MatchSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Mid           string                 `protobuf:"bytes,2,opt,name=mid,proto3" json:"mid,omitempty"`
	MapName       string                 `protobuf:"bytes,3,opt,name=map_name,json=mapName,proto3" json:"map_name,omitempty"`
	MatchStart    string                 `protobuf:"bytes,4,opt,name=match_start,json=matchStart,proto3" json:"match_start,omitempty"`
	PlayerCount   int32                  `protobuf:"varint,5,opt,name=player_count,json=playerCount,proto3" json:"player_count,omitempty"`
	TokenId       int32                  `protobuf:"varint,6,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchSummary) Reset() {
	*x = MatchSummary{}
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchSummary) ProtoMessage() {}

func (x *MatchSummary) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchSummary.ProtoReflect.Descriptor instead.
func (*MatchSummary) Descriptor() ([]byte, []int) {
	return file_internal_client_matchapi_proto_match_service_proto_rawDescGZIP(), []int{6}
}

func (x *MatchSummary) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MatchSummary) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

func (x *MatchSummary) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *MatchSummary) GetMatchStart() string {
	if x != nil {
		return x.MatchStart
	}
	return ""
}

func (x *MatchSummary) GetPlayerCount() int32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

func (x *MatchSummary) GetTokenId() int32 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

type ListMatchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*MatchSummary        `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMatchesResponse) Reset() {
	*x = ListMatchesResponse{}
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMatchesResponse) ProtoMessage() {}

func (x *ListMatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMatchesResponse.ProtoReflect.Descriptor instead.
func (*ListMatchesResponse) Descriptor() ([]byte, []int) {
	return file_internal_client_matchapi_proto_match_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListMatchesResponse) GetMatches() []*MatchSummary {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *ListMatchesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListMatchesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type MatchDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       int32                  `protobuf:"varint,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchDetailRequest) Reset() {
	*x = MatchDetailRequest{}
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchDetailRequest) ProtoMessage() {}

func (x *MatchDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchDetailRequest.ProtoReflect.Descriptor instead.
func (*MatchDetailRequest) Descriptor() ([]byte, []int) {
	return file_internal_client_matchapi_proto_match_service_proto_rawDescGZIP(), []int{8}
}

func (x *MatchDetailRequest) GetMatchId() int32 {
	if x != nil {
		return x.MatchId
	}
	return 0
}

type PlayerResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerName    string                 `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	CharacterName string                 `protobuf:"bytes,2,opt,name=character_name,json=characterName,proto3" json:"character_name,omitempty"`
	Kills         int32                  `protobuf:"varint,3,opt,name=kills,proto3" json:"kills,omitempty"`
	Assists       int32                  `protobuf:"varint,4,opt,name=assists,proto3" json:"assists,omitempty"`
	Knockdowns    int32                  `protobuf:"varint,5,opt,name=knockdowns,proto3" json:"knockdowns,omitempty"`
	DamageDealt   int32                  `protobuf:"varint,6,opt,name=damage_dealt,json=damageDealt,proto3" json:"damage_dealt,omitempty"`
	SurvivalTime  int32                  `protobuf:"varint,7,opt,name=survival_time,json=survivalTime,proto3" json:"survival_time,omitempty"`
	TeamName      string                 `protobuf:"bytes,8,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	TeamPlacement int32                  `protobuf:"varint,9,opt,name=team_placement,json=teamPlacement,proto3" json:"team_placement,omitempty"`
	NidHash       string                 `protobuf:"bytes,10,opt,name=nid_hash,json=nidHash,proto3" json:"nid_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerResult) Reset() {
	*x = PlayerResult{}
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerResult) ProtoMessage() {}

func (x *PlayerResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerResult.ProtoReflect.Descriptor instead.
func (*PlayerResult) Descriptor() ([]byte, []int) {
	return file_internal_client_matchapi_proto_match_service_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerResult) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *PlayerResult) GetCharacterName() string {
	if x != nil {
		return x.CharacterName
	}
	return ""
}

func (x *PlayerResult) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *PlayerResult) GetAssists() int32 {
	if x != nil {
		return x.Assists
	}
	return 0
}

func (x *PlayerResult) GetKnockdowns() int32 {
	if x != nil {
		return x.Knockdowns
	}
	return 0
}

func (x *PlayerResult) GetDamageDealt() int32 {
	if x != nil {
		return x.DamageDealt
	}
	return 0
}

func (x *PlayerResult) GetSurvivalTime() int32 {
	if x != nil {
		return x.SurvivalTime
	}
	return 0
}

func (x *PlayerResult) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

func (x *PlayerResult) GetTeamPlacement() int32 {
	if x != nil {
		return x.TeamPlacement
	}
	return 0
}

func (x *PlayerResult) GetNidHash() string {
	if x != nil {
		return x.NidHash
	}
	return ""
}

type MatchDetailResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MatchId          int32                  `protobuf:"varint,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Mid              string                 `protobuf:"bytes,2,opt,name=mid,proto3" json:"mid,omitempty"`
	MapName          string                 `protobuf:"bytes,3,opt,name=map_name,json=mapName,proto3" json:"map_name,omitempty"`
	AimAssistAllowed bool                   `protobuf:"varint,4,opt,name=aim_assist_allowed,json=aimAssistAllowed,proto3" json:"aim_assist_allowed,omitempty"`
	MatchStart       string                 `protobuf:"bytes,5,opt,name=match_start,json=matchStart,proto3" json:"match_start,omitempty"`
	Players          []*PlayerResult        `protobuf:"bytes,6,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MatchDetailResponse) Reset() {
	*x = MatchDetailResponse{}
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchDetailResponse) ProtoMessage() {}

func (x *MatchDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchDetailResponse.ProtoReflect.Descriptor instead.
func (*MatchDetailResponse) Descriptor() ([]byte, []int) {
	return file_internal_client_matchapi_proto_match_service_proto_rawDescGZIP(), []int{10}
}

func (x *MatchDetailResponse) GetMatchId() int32 {
	if x != nil {
		return x.MatchId
	}
	return 0
}

func (x *MatchDetailResponse) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

func (x *MatchDetailResponse) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *MatchDetailResponse) GetAimAssistAllowed() bool {
	if x != nil {
		return x.AimAssistAllowed
	}
	return false
}

func (x *MatchDetailResponse) GetMatchStart() string {
	if x != nil {
		return x.MatchStart
	}
	return ""
}

func (x *MatchDetailResponse) GetPlayers() []*PlayerResult {
	if x != nil {
		return x.Players
	}
	return nil
}

type MatchStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	MapName       string                 `protobuf:"bytes,3,opt,name=map_name,json=mapName,proto3" json:"map_name,omitempty"`
	MinKills      int32                  `protobuf:"varint,4,opt,name=min_kills,json=minKills,proto3" json:"min_kills,omitempty"`
	MaxKills      int32                  `protobuf:"varint,5,opt,name=max_kills,json=maxKills,proto3" json:"max_kills,omitempty"`
	PlayerHash    string                 `protobuf:"bytes,6,opt,name=player_hash,json=playerHash,proto3" json:"player_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchStatsRequest) Reset() {
	*x = MatchStatsRequest{}
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStatsRequest) ProtoMessage() {}

func (x *MatchStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStatsRequest.ProtoReflect.Descriptor instead.
func (*MatchStatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_client_matchapi_proto_match_service_proto_rawDescGZIP(), []int{11}
}

func (x *MatchStatsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *MatchStatsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *MatchStatsRequest) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *MatchStatsRequest) GetMinKills() int32 {
	if x != nil {
		return x.MinKills
	}
	return 0
}

func (x *MatchStatsRequest) GetMaxKills() int32 {
	if x != nil {
		return x.MaxKills
	}
	return 0
}

func (x *MatchStatsRequest) GetPlayerHash() string {
	if x != nil {
		return x.PlayerHash
	}
	return ""
}

type MatchStatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalMatches    int32                  `protobuf:"varint,1,opt,name=total_matches,json=totalMatches,proto3" json:"total_matches,omitempty"`
	TotalPlayers    int32                  `protobuf:"varint,2,opt,name=total_players,json=totalPlayers,proto3" json:"total_players,omitempty"`
	AvgKills        float64                `protobuf:"fixed64,3,opt,name=avg_kills,json=avgKills,proto3" json:"avg_kills,omitempty"`
	AvgDamage       float64                `protobuf:"fixed64,4,opt,name=avg_damage,json=avgDamage,proto3" json:"avg_damage,omitempty"`
	AvgSurvivalTime float64                `protobuf:"fixed64,5,opt,name=avg_survival_time,json=avgSurvivalTime,proto3" json:"avg_survival_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MatchStatsResponse) Reset() {
	*x = MatchStatsResponse{}
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStatsResponse) ProtoMessage() {}

func (x *MatchStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStatsResponse.ProtoReflect.Descriptor instead.
func (*MatchStatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_client_matchapi_proto_match_service_proto_rawDescGZIP(), []int{12}
}

func (x *MatchStatsResponse) GetTotalMatches() int32 {
	if x != nil {
		return x.TotalMatches
	}
	return 0
}

func (x *MatchStatsResponse) GetTotalPlayers() int32 {
	if x != nil {
		return x.TotalPlayers
	}
	return 0
}

func (x *MatchStatsResponse) GetAvgKills() float64 {
	if x != nil {
		return x.AvgKills
	}
	return 0
}

func (x *MatchStatsResponse) GetAvgDamage() float64 {
	if x != nil {
		return x.AvgDamage
	}
	return 0
}

func (x *MatchStatsResponse) GetAvgSurvivalTime() float64 {
	if x != nil {
		return x.AvgSurvivalTime
	}
	return 0
}

type PlayerStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerHash    string                 `protobuf:"bytes,1,opt,name=player_hash,json=playerHash,proto3" json:"player_hash,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerStatsRequest) Reset() {
	*x = PlayerStatsRequest{}
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStatsRequest) ProtoMessage() {}

func (x *PlayerStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStatsRequest.ProtoReflect.Descriptor instead.
func (*PlayerStatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_client_matchapi_proto_match_service_proto_rawDescGZIP(), []int{13}
}

func (x *PlayerStatsRequest) GetPlayerHash() string {
	if x != nil {
		return x.PlayerHash
	}
	return ""
}

func (x *PlayerStatsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *PlayerStatsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type PlayerStatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlayerHash      string                 `protobuf:"bytes,1,opt,name=player_hash,json=playerHash,proto3" json:"player_hash,omitempty"`
	MatchesPlayed   int32                  `protobuf:"varint,2,opt,name=matches_played,json=matchesPlayed,proto3" json:"matches_played,omitempty"`
	TotalKills      int32                  `protobuf:"varint,3,opt,name=total_kills,json=totalKills,proto3" json:"total_kills,omitempty"`
	TotalDamage     int32                  `protobuf:"varint,4,opt,name=total_damage,json=totalDamage,proto3" json:"total_damage,omitempty"`
	AvgDamage       float64                `protobuf:"fixed64,5,opt,name=avg_damage,json=avgDamage,proto3" json:"avg_damage,omitempty"`
	AvgSurvivalTime float64                `protobuf:"fixed64,6,opt,name=avg_survival_time,json=avgSurvivalTime,proto3" json:"avg_survival_time,omitempty"`
	TotalWins       int32                  `protobuf:"varint,7,opt,name=total_wins,json=totalWins,proto3" json:"total_wins,omitempty"`
	TopCharacters   []*CharacterStats      `protobuf:"bytes,8,rep,name=top_characters,json=topCharacters,proto3" json:"top_characters,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlayerStatsResponse) Reset() {
	*x = PlayerStatsResponse{}
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStatsResponse) ProtoMessage() {}

func (x *PlayerStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStatsResponse.ProtoReflect.Descriptor instead.
func (*PlayerStatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_client_matchapi_proto_match_service_proto_rawDescGZIP(), []int{14}
}

func (x *PlayerStatsResponse) GetPlayerHash() string {
	if x != nil {
		return x.PlayerHash
	}
	return ""
}

func (x *PlayerStatsResponse) GetMatchesPlayed() int32 {
	if x != nil {
		return x.MatchesPlayed
	}
	return 0
}

func (x *PlayerStatsResponse) GetTotalKills() int32 {
	if x != nil {
		return x.TotalKills
	}
	return 0
}

func (x *PlayerStatsResponse) GetTotalDamage() int32 {
	if x != nil {
		return x.TotalDamage
	}
	return 0
}

func (x *PlayerStatsResponse) GetAvgDamage() float64 {
	if x != nil {
		return x.AvgDamage
	}
	return 0
}

func (x *PlayerStatsResponse) GetAvgSurvivalTime() float64 {
	if x != nil {
		return x.AvgSurvivalTime
	}
	return 0
}

func (x *PlayerStatsResponse) GetTotalWins() int32 {
	if x != nil {
		return x.TotalWins
	}
	return 0
}

func (x *PlayerStatsResponse) GetTopCharacters() []*CharacterStats {
	if x != nil {
		return x.TopCharacters
	}
	return nil
}

type CharacterStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterName string                 `protobuf:"bytes,1,opt,name=character_name,json=characterName,proto3" json:"character_name,omitempty"`
	Matches       int32                  `protobuf:"varint,2,opt,name=matches,proto3" json:"matches,omitempty"`
	Kills         int32                  `protobuf:"varint,3,opt,name=kills,proto3" json:"kills,omitempty"`
	Picks         int32                  `protobuf:"varint,4,opt,name=picks,proto3" json:"picks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterStats) Reset() {
	*x = CharacterStats{}
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterStats) ProtoMessage() {}

func (x *CharacterStats) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_matchapi_proto_match_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterStats.ProtoReflect.Descriptor instead.
func (*CharacterStats) Descriptor() ([]byte, []int) {
	return file_internal_client_matchapi_proto_match_service_proto_rawDescGZIP(), []int{15}
}

func (x *CharacterStats) GetCharacterName() string {
	if x != nil {
		return x.CharacterName
	}
	return ""
}

func (x *CharacterStats) GetMatches() int32 {
	if x != nil {
		return x.Matches
	}
	return 0
}

func (x *CharacterStats) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *CharacterStats) GetPicks() int32 {
	if x != nil {
		return x.Picks
	}
	return 0
}

var File_internal_client_matchapi_proto_match_service_proto protoreflect.FileDescriptor

const file_internal_client_matchapi_proto_match_service_proto_rawDesc = "" +
	"\n" +
	"2internal/client/matchapi/proto/match_service.proto\x12\bmatchapi\"\xb6\x01\n" +
	"\x0fAddTokenRequest\x12\x1e\n" +
	"\n" +
	"activation\x18\x01 \x01(\tR\n" +
	"activation\x12\x1e\n" +
	"\n" +
	"expiration\x18\x02 \x01(\tR\n" +
	"expiration\x12\x1f\n" +
	"\vstats_token\x18\x03 \x01(\tR\n" +
	"statsToken\x12\x1f\n" +
	"\vadmin_token\x18\x04 \x01(\tR\n" +
	"adminToken\x12!\n" +
	"\fplayer_token\x18\x05 \x01(\tR\vplayerToken\"G\n" +
	"\x10AddTokenResponse\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\x05R\atokenId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"p\n" +
	"\x11ListTokensRequest\x12\x1f\n" +
	"\vonly_active\x18\x01 \x01(\bR\n" +
	"onlyActive\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"x\n" +
	"\tTokenInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1e\n" +
	"\n" +
	"activation\x18\x02 \x01(\tR\n" +
	"activation\x12\x1e\n" +
	"\n" +
	"expiration\x18\x03 \x01(\tR\n" +
	"expiration\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\"\x8a\x01\n" +
	"\x12ListTokensResponse\x12+\n" +
	"\x06tokens\x18\x01 \x03(\v2\x13.matchapi.TokenInfoR\x06tokens\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\xe1\x01\n" +
	"\x12ListMatchesRequest\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\x12\x19\n" +
	"\bmap_name\x18\x03 \x01(\tR\amapName\x12\x1f\n" +
	"\vplayer_hash\x18\x04 \x01(\tR\n" +
	"playerHash\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x06 \x01(\tR\tpageToken\x12\x19\n" +
	"\btoken_id\x18\a \x01(\x05R\atokenId\"\xaa\x01\n" +
	"\fMatchSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x10\n" +
	"\x03mid\x18\x02 \x01(\tR\x03mid\x12\x19\n" +
	"\bmap_name\x18\x03 \x01(\tR\amapName\x12\x1f\n" +
	"\vmatch_start\x18\x04 \x01(\tR\n" +
	"matchStart\x12!\n" +
	"\fplayer_count\x18\x05 \x01(\x05R\vplayerCount\x12\x19\n" +
	"\btoken_id\x18\x06 \x01(\x05R\atokenId\"\x90\x01\n" +
	"\x13ListMatchesResponse\x120\n" +
	"\amatches\x18\x01 \x03(\v2\x16.matchapi.MatchSummaryR\amatches\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"/\n" +
	"\x12MatchDetailRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\x05R\amatchId\"\xcd\x02\n" +
	"\fPlayerResult\x12\x1f\n" +
	"\vplayer_name\x18\x01 \x01(\tR\n" +
	"playerName\x12%\n" +
	"\x0echaracter_name\x18\x02 \x01(\tR\rcharacterName\x12\x14\n" +
	"\x05kills\x18\x03 \x01(\x05R\x05kills\x12\x18\n" +
	"\aassists\x18\x04 \x01(\x05R\aassists\x12\x1e\n" +
	"\n" +
	"knockdowns\x18\x05 \x01(\x05R\n" +
	"knockdowns\x12!\n" +
	"\fdamage_dealt\x18\x06 \x01(\x05R\vdamageDealt\x12#\n" +
	"\rsurvival_time\x18\a \x01(\x05R\fsurvivalTime\x12\x1b\n" +
	"\tteam_name\x18\b \x01(\tR\bteamName\x12%\n" +
	"\x0eteam_placement\x18\t \x01(\x05R\rteamPlacement\x12\x19\n" +
	"\bnid_hash\x18\n" +
	" \x01(\tR\anidHash\"\xde\x01\n" +
	"\x13MatchDetailResponse\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\x05R\amatchId\x12\x10\n" +
	"\x03mid\x18\x02 \x01(\tR\x03mid\x12\x19\n" +
	"\bmap_name\x18\x03 \x01(\tR\amapName\x12,\n" +
	"\x12aim_assist_allowed\x18\x04 \x01(\bR\x10aimAssistAllowed\x12\x1f\n" +
	"\vmatch_start\x18\x05 \x01(\tR\n" +
	"matchStart\x120\n" +
	"\aplayers\x18\x06 \x03(\v2\x16.matchapi.PlayerResultR\aplayers\"\xc3\x01\n" +
	"\x11MatchStatsRequest\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\x12\x19\n" +
	"\bmap_name\x18\x03 \x01(\tR\amapName\x12\x1b\n" +
	"\tmin_kills\x18\x04 \x01(\x05R\bminKills\x12\x1b\n" +
	"\tmax_kills\x18\x05 \x01(\x05R\bmaxKills\x12\x1f\n" +
	"\vplayer_hash\x18\x06 \x01(\tR\n" +
	"playerHash\"\xc6\x01\n" +
	"\x12MatchStatsResponse\x12#\n" +
	"\rtotal_matches\x18\x01 \x01(\x05R\ftotalMatches\x12#\n" +
	"\rtotal_players\x18\x02 \x01(\x05R\ftotalPlayers\x12\x1b\n" +
	"\tavg_kills\x18\x03 \x01(\x01R\bavgKills\x12\x1d\n" +
	"\n" +
	"avg_damage\x18\x04 \x01(\x01R\tavgDamage\x12*\n" +
	"\x11avg_survival_time\x18\x05 \x01(\x01R\x0favgSurvivalTime\"o\n" +
	"\x12PlayerStatsRequest\x12\x1f\n" +
	"\vplayer_hash\x18\x01 \x01(\tR\n" +
	"playerHash\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\"\xcc\x02\n" +
	"\x13PlayerStatsResponse\x12\x1f\n" +
	"\vplayer_hash\x18\x01 \x01(\tR\n" +
	"playerHash\x12%\n" +
	"\x0ematches_played\x18\x02 \x01(\x05R\rmatchesPlayed\x12\x1f\n" +
	"\vtotal_kills\x18\x03 \x01(\x05R\n" +
	"totalKills\x12!\n" +
	"\ftotal_damage\x18\x04 \x01(\x05R\vtotalDamage\x12\x1d\n" +
	"\n" +
	"avg_damage\x18\x05 \x01(\x01R\tavgDamage\x12*\n" +
	"\x11avg_survival_time\x18\x06 \x01(\x01R\x0favgSurvivalTime\x12\x1d\n" +
	"\n" +
	"total_wins\x18\a \x01(\x05R\ttotalWins\x12?\n" +
	"\x0etop_characters\x18\b \x03(\v2\x18.matchapi.CharacterStatsR\rtopCharacters\"}\n" +
	"\x0eCharacterStats\x12%\n" +
	"\x0echaracter_name\x18\x01 \x01(\tR\rcharacterName\x12\x18\n" +
	"\amatches\x18\x02 \x01(\x05R\amatches\x12\x14\n" +
	"\x05kills\x18\x03 \x01(\x05R\x05kills\x12\x14\n" +
	"\x05picks\x18\x04 \x01(\x05R\x05picks2\xd0\x03\n" +
	"\fMatchService\x12A\n" +
	"\bAddToken\x12\x19.matchapi.AddTokenRequest\x1a\x1a.matchapi.AddTokenResponse\x12G\n" +
	"\n" +
	"ListTokens\x12\x1b.matchapi.ListTokensRequest\x1a\x1c.matchapi.ListTokensResponse\x12J\n" +
	"\vListMatches\x12\x1c.matchapi.ListMatchesRequest\x1a\x1d.matchapi.ListMatchesResponse\x12J\n" +
	"\rGetMatchStats\x12\x1b.matchapi.MatchStatsRequest\x1a\x1c.matchapi.MatchStatsResponse\x12M\n" +
	"\x0eGetMatchDetail\x12\x1c.matchapi.MatchDetailRequest\x1a\x1d.matchapi.MatchDetailResponse\x12M\n" +
	"\x0eGetPlayerStats\x12\x1c.matchapi.PlayerStatsRequest\x1a\x1d.matchapi.PlayerStatsResponseBWZUgithub.com/rzhaka-turiki/rzhaka_tournaments/internal/client/matchapi/proto;matchapipbb\x06proto3"

var (
	file_internal_client_matchapi_proto_match_service_proto_rawDescOnce sync.Once
	file_internal_client_matchapi_proto_match_service_proto_rawDescData []byte
)

func file_internal_client_matchapi_proto_match_service_proto_rawDescGZIP() []byte {
	file_internal_client_matchapi_proto_match_service_proto_rawDescOnce.Do(func() {
		file_internal_client_matchapi_proto_match_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_client_matchapi_proto_match_service_proto_rawDesc), len(file_internal_client_matchapi_proto_match_service_proto_rawDesc)))
	})
	return file_internal_client_matchapi_proto_match_service_proto_rawDescData
}

var file_internal_client_matchapi_proto_match_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_internal_client_matchapi_proto_match_service_proto_goTypes = []any{
	(*AddTokenRequest)(nil),     // 0: matchapi.AddTokenRequest
	(*AddTokenResponse)(nil),    // 1: matchapi.AddTokenResponse
	(*ListTokensRequest)(nil),   // 2: matchapi.ListTokensRequest
	(*TokenInfo)(nil),           // 3: matchapi.TokenInfo
	(*ListTokensResponse)(nil),  // 4: matchapi.ListTokensResponse
	(*ListMatchesRequest)(nil),  // 5: matchapi.ListMatchesRequest
	(*MatchSummary)(nil),        // 6: matchapi.MatchSummary
	(*ListMatchesResponse)(nil), // 7: matchapi.ListMatchesResponse
	(*MatchDetailRequest)(nil),  // 8: matchapi.MatchDetailRequest
	(*PlayerResult)(nil),        // 9: matchapi.PlayerResult
	(*MatchDetailResponse)(nil), // 10: matchapi.MatchDetailResponse
	(*MatchStatsRequest)(nil),   // 11: matchapi.MatchStatsRequest
	(*MatchStatsResponse)(nil),  // 12: matchapi.MatchStatsResponse
	(*PlayerStatsRequest)(nil),  // 13: matchapi.PlayerStatsRequest
	(*PlayerStatsResponse)(nil), // 14: matchapi.PlayerStatsResponse
	(*CharacterStats)(nil),      // 15: matchapi.CharacterStats
}
var file_internal_client_matchapi_proto_match_service_proto_depIdxs = []int32{
	3,  // 0: matchapi.ListTokensResponse.tokens:type_name -> matchapi.TokenInfo
	6,  // 1: matchapi.ListMatchesResponse.matches:type_name -> matchapi.MatchSummary
	9,  // 2: matchapi.MatchDetailResponse.players:type_name -> matchapi.PlayerResult
	15, // 3: matchapi.PlayerStatsResponse.top_characters:type_name -> matchapi.CharacterStats
	0,  // 4: matchapi.MatchService.AddToken:input_type -> matchapi.AddTokenRequest
	2,  // 5: matchapi.MatchService.ListTokens:input_type -> matchapi.ListTokensRequest
	5,  // 6: matchapi.MatchService.ListMatches:input_type -> matchapi.ListMatchesRequest
	11, // 7: matchapi.MatchService.GetMatchStats:input_type -> matchapi.MatchStatsRequest
	8,  // 8: matchapi.MatchService.GetMatchDetail:input_type -> matchapi.MatchDetailRequest
	13, // 9: matchapi.MatchService.GetPlayerStats:input_type -> matchapi.PlayerStatsRequest
	1,  // 10: matchapi.MatchService.AddToken:output_type -> matchapi.AddTokenResponse
	4,  // 11: matchapi.MatchService.ListTokens:output_type -> matchapi.ListTokensResponse
	7,  // 12: matchapi.MatchService.ListMatches:output_type -> matchapi.ListMatchesResponse
	12, // 13: matchapi.MatchService.GetMatchStats:output_type -> matchapi.MatchStatsResponse
	10, // 14: matchapi.MatchService.GetMatchDetail:output_type -> matchapi.MatchDetailResponse
	14, // 15: matchapi.MatchService.GetPlayerStats:output_type -> matchapi.PlayerStatsResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_internal_client_matchapi_proto_match_service_proto_init() }
func file_internal_client_matchapi_proto_match_service_proto_init() {
	if File_internal_client_matchapi_proto_match_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_client_matchapi_proto_match_service_proto_rawDesc), len(file_internal_client_matchapi_proto_match_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_client_matchapi_proto_match_service_proto_goTypes,
		DependencyIndexes: file_internal_client_matchapi_proto_match_service_proto_depIdxs,
		MessageInfos:      file_internal_client_matchapi_proto_match_service_proto_msgTypes,
	}.Build()
	File_internal_client_matchapi_proto_match_service_proto = out.File
	file_internal_client_matchapi_proto_match_service_proto_goTypes = nil
	file_internal_client_matchapi_proto_match_service_proto_depIdxs = nil
}
